// Paleta oficial ReportARG
export const colors = {
  primary: "#2D3A8C",
  primaryLight: "#f0f6ff",
  primaryBorder: "#c8dff7",
  accent: "#5BAAE8",
  warning: "#F5C842",
  warningBg: "#fffbe6",
  warningBorder: "#F5C842",
  warningText: "#7a6000",
  danger: "#C0392B",
  dangerBg: "#fee2e2",
  dangerBorder: "#fecaca",
  success: "#1A7A3C",
  border: "#e8f0fa",
  bg: "#f7faff",
  textPrimary: "#2D3A8C",
  textSecondary: "#555",
  textMuted: "#aaa",
};

// Botones reutilizables
export const btnStyles = {
  primary: {
    padding: "9px 20px",
    borderRadius: 8,
    border: "none",
    background: colors.primary,
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondary: {
    padding: "9px 20px",
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    background: "#fff",
    color: colors.textSecondary,
    fontSize: 13,
    cursor: "pointer",
  },
  edit: {
    padding: "5px 12px",
    borderRadius: 6,
    border: `1px solid ${colors.primaryBorder}`,
    background: colors.primaryLight,
    color: colors.primary,
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 500,
  },
  danger: {
    padding: "5px 12px",
    borderRadius: 6,
    border: `1px solid ${colors.dangerBorder}`,
    background: colors.dangerBg,
    color: colors.danger,
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 500,
  },
  small: {
    todo: {
      fontSize: 11,
      padding: "3px 8px",
      borderRadius: 6,
      border: `1px solid ${colors.primaryBorder}`,
      background: colors.primaryLight,
      color: colors.primary,
      cursor: "pointer",
    },
    limpiar: {
      fontSize: 11,
      padding: "3px 8px",
      borderRadius: 6,
      border: `1px solid ${colors.dangerBorder}`,
      background: colors.dangerBg,
      color: colors.danger,
      cursor: "pointer",
    },
  },
};